### ISSUE TITLE
Outside SLAC network

### ISSUE THREAD

**Issue by kadamidi** [slaclab/dev-board-common-platform#1]
Hello,

I am wondering if it is possible to build your projects while being outside the slac network.

Regards
Kosmas

**Comment by till-s** [comment]
On 09/22/2018 08:46 AM, kadamidi wrote:
>
> Hello,
>
> I am wondering if it is possible to build your projects while being 
> outside the slac network.
>

I don't see why you shouldn't be able to do that - provided that you 
have a vivado license
and recent git with lfs support.

HTH
- Till

**Comment by slacrherbst** [comment]
Yes a lot of our collaborators build projects like the common platform 
outside the SLAC network. There are not any dependencies to the SLAC 
network. You will require your own license.

**Comment by kadamidi** [comment]
Oh yes you are both right thank you.
Kosmas

**Comment by till-s** [comment]
It's been a while but I wanted to comment on one issue you might encounter from outside:

there are a few '.lfsconfig' files (and maybe '.gitmodules' also) which contain 'git@github...' links and break cloning via https. You can manually massage these files. The next release (which should come soon) will have this fixed!
